apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-web
    spec:
      containers:
      - name: app-with-argocd
        image: sungchilll/app-with-argocd:b16d2a3a2e24c82deee1cac2ab93a98f434a7dc5
